services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finance-backend
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/db-personal-finance-manager
      - SPRING_DATASOURCE_USERNAME=personal_finance_manager_admin
      - SPRING_DATASOURCE_PASSWORD=personal_finance_manager_admin
      - SPRING_FLYWAY_URL=jdbc:postgresql://host.docker.internal:5432/db-personal-finance-manager
      - SPRING_FLYWAY_USER=personal_finance_manager_admin
      - SPRING_FLYWAY_PASSWORD=personal_finance_manager_admin

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finance-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
